Traceback (most recent call last):
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
uploaded_file = uploader.value['Analyse_TechnicoEconomique.xlsx']
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_197601/1926846823.py[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m [0muploaded_file[0m [0;34m=[0m [0muploader[0m[0;34m.[0m[0mvalue[0m[0;34m[[0m[0;34m'Analyse_TechnicoEconomique.xlsx'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mKeyError[0m: 'Analyse_TechnicoEconomique.xlsx'
KeyError: 'Analyse_TechnicoEconomique.xlsx'

